=== dennyhina/depunit/trunk/doc/depunit_1_0.dtd
<!ELEMENT suite (classGroup*,run+)>
	<!ATTLIST suite name CDATA #REQUIRED>
	<!ATTLIST suite verbose CDATA #IMPLIED>

<!ELEMENT classGroup (class+)>
	<!ATTLIST classGroup name CDATA #REQUIRED>
	
<!ELEMENT run (classes,tests?)>
	<!ATTLIST run name CDATA #REQUIRED>

<!ELEMENT classes (includeGroup?,class*)>

<!ELEMENT includeGroup (#PCDATA)>

<!ELEMENT class (value*|driver)>
	<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>
	<!ATTLIST value name CDATA #REQUIRED>
	
<!ELEMENT driver (data*|value*)>
	<!ATTLIST driver class CDATA #IMPLIED>

<!ELEMENT data (value+)>

<!ELEMENT tests (method+)>

<!ELEMENT method (#PCDATA)>

=== dennyhina/depunit/test.xml
<!DOCTYPE suite SYSTEM "http://depunit.googlecode.com/svn/trunk/doc/depunit_1_0.dtd">

<!--
Needed test cases
One method loops
Loop at the beginning
Loop at the end
-->
<suite name="suite name" verbose="1">
	<classGroup name="login_group">
		<class name="LoginTest"/>
		<class name="LoginTestPart2"/>
	</classGroup>
	
	<run name="Pattern run">
		<classes>
			<class name="CleanupTest"/>
			<class name="LoginTest"/>
			<class name="LoginTestPart2"/>
			<class name="Project"/>
		</classes>
		
		<tests pattern="Project\.create.*"/>
	</run>
	
	<!-- <run name="Data Driver Run">
		<classes>
			<class name="DataDriverTest">
				<driver class="TestDataDriver"/>
			</class>
		</classes>
	</run>
	
	<run name="First Run">
		<classes>
			<includeGroup>login_group</includeGroup>
			
			<class name="LoginTest">
				<value name="UserName">Sammy</value>
				<value name="Password">secret</value>
				<value name="test">4</value>
			</class>
		</classes>
		
	</run>
	
	<run name="Cleanup Run">
		<classes>
			<class name="CleanupTest"/>
		</classes>
	</run>
	
	<run name="Fail run">
		<classes>
			<class name="UnitTest"/>
		</classes>
	</run>
	
	<run name="Second Run">
		<classes>
			<class name="LoginTest">
				<value name="UserName">MyUserName</value>
				<value name="Password">mysecret</value>
			</class>
		</classes>
		
		<tests>
			<method>LoginTest.login</method>
		</tests>
	</run> -->
	
	<!-- <run name="Repeat run with cleanup">
		<classes>
			<class name="RepeatCleanup">
				<driver>
					<data>
						<value name="MyData">Here is my data</value>
					</data>
					<data>
						<value name="MyData">Here is my data2</value>
					</data>
				</driver>
			</class>
		</classes>
		
	</run> -->
	
	<run name="Repeat run with cleanup">
		<classes>
			<class name="RepeatCleanup">
				<driver>
					<data>
						<value name="MyData">Here is my data</value>
					</data>
					<data>
						<value name="MyData">Here is my data2</value>
					</data>
				</driver>
			</class>
			<class name="TestDependOnDataDriver" />
		</classes>
		<tests>
			<method>TestDependOnDataDriver.myTest</method>
		</tests>
	</run>
	
	<!-- <run name="Repeat run">
		<classes>
			<class name="LoginTest">
				<value name="UserName">Sammy</value>
				<value name="Password">secret</value>
				<value name="test">4</value>
			</class>
			
			<class name="LoginTestPart2">
				<driver>
					<data>
						<value name="MyData">Here is my data</value>
					</data>
					<data>
						<value name="MyData">Here is my data2</value>
					</data>
				</driver>
			</class>
		</classes>
		
	</run> -->
	
	<!-- <run name="fail login">
		<classes>
			<class name="LoginTest" >
				<value name="UserName">Sammy</value>
				<value name="Password">secret</value>
				<value name="Fail">true</value>
			</class>
			<class name="Project">
				<driver>
					<data>
						<value name="ProjectName">my project</value>
					</data>
				</driver>
			</class>
		</classes>
	</run> -->
	
</suite>
